apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: datacontrollers.arcdata.microsoft.com
spec:
  group: arcdata.microsoft.com
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: State
      type: string
      jsonPath: .status.state
  conversion:
    strategy: None
  names:
    kind: datacontroller
    plural: datacontrollers
  scope: Namespaced
