apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sqlmanagedinstances.sql.arcdata.microsoft.com
spec:
  group: sql.arcdata.microsoft.com
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Status
      type: string
      jsonPath: ".status.state"
    - name: Replicas
      type: string
      jsonPath: ".status.readyReplicas"
    - name: Primary-Endpoint
      type: string
      jsonPath: ".status.primaryEndpoint"
    - name: Age
      type: date
      jsonPath: ".metadata.creationTimestamp"
  conversion:
    strategy: None
  names:
    kind: sqlmanagedinstance
    plural: sqlmanagedinstances
    shortNames:
    - sqlmi
  scope: Namespaced
